services:
  - type: web
    name: sedeges-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
